# Generated by Django 2.2 on 2019-06-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20190625_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.IntegerField(default='3503')),
                ('police_station_name', models.CharField(max_length=64)),
                ('police_station_code', models.CharField(max_length=10)),
                ('police_station_city', models.CharField(max_length=250)),
                ('complaints_name', models.CharField(max_length=64)),
                ('Father_Mother_name', models.CharField(max_length=64)),
                ('complainants_address', models.CharField(max_length=64)),
                ('complainants_mobile_number', models.CharField(max_length=15)),
                ('place_of_loss', models.CharField(max_length=64)),
                ('Date', models.DateField()),
                ('time', models.TimeField()),
                ('case_categeory', models.CharField(max_length=64)),
                ('lost_articles', models.CharField(max_length=254)),
                ('complet_description', models.CharField(max_length=254)),
                ('fir_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='display',
            name='number_id',
            field=models.IntegerField(default='5144', unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='reg_id',
            field=models.IntegerField(default='6348'),
        ),
    ]
