# Generated by Django 2.2.1 on 2019-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20190625_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='number_id',
            field=models.IntegerField(default='2731', unique=True),
        ),
        migrations.AlterField(
            model_name='fir_details',
            name='fir_number',
            field=models.IntegerField(default='7360'),
        ),
        migrations.AlterField(
            model_name='register',
            name='reg_id',
            field=models.IntegerField(default='0268'),
        ),
    ]
