# Generated by Django 2.2.1 on 2019-06-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20190625_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir_details',
            old_name='Father_Mother_name',
            new_name='Father_name',
        ),
        migrations.AlterField(
            model_name='display',
            name='number_id',
            field=models.IntegerField(default='7181', unique=True),
        ),
        migrations.AlterField(
            model_name='fir_details',
            name='fir_number',
            field=models.IntegerField(default='6257'),
        ),
        migrations.AlterField(
            model_name='register',
            name='reg_id',
            field=models.IntegerField(default='8929'),
        ),
    ]
